load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")
load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")
load("@fbcode_macros//build_defs/lib:re_test_utils.bzl", "re_test_utils")

oncall("fbcode_entropy_wardens_folly")

cpp_unittest(
    name = "accept_routing_handler_test",
    srcs = ["AcceptRoutingHandlerTest.cpp"],
    remote_execution = re_test_utils.remote_execution_linux_default(),
    deps = [
        ":mocks",
    ],
)

cpp_unittest(
    name = "bootstrap_test",
    srcs = ["BootstrapTest.cpp"],
    remote_execution = re_test_utils.remote_execution_linux_default(),
    deps = [
        "//folly:string",
        "//folly/experimental:test_util",
        "//folly/portability:gtest",
        "//wangle/bootstrap:client_bootstrap",
        "//wangle/bootstrap:server_bootstrap",
        "//wangle/channel:handler",
    ],
    external_deps = [
        ("boost", None, "boost_thread"),
        "glog",
    ],
)

cpp_library(
    name = "mocks",
    headers = ["Mocks.h"],
    exported_deps = [
        "//folly/portability:gmock",
        "//folly/portability:gtest",
        "//wangle/bootstrap:accept_routing_handler",
        "//wangle/bootstrap:client_bootstrap",
        "//wangle/bootstrap:routing_data_handler",
        "//wangle/bootstrap:server_bootstrap",
        "//wangle/channel:pipeline",
        "//wangle/channel/test:mocks",
    ],
    exported_external_deps = [
        ("boost", None, "boost_thread"),
    ],
)
