load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")
load("@fbcode_macros//build_defs/lib:re_test_utils.bzl", "re_test_utils")

oncall("fbcode_entropy_wardens_folly")

cpp_unittest(
    name = "ServiceTest",
    srcs = ["ServiceTest.cpp"],
    remote_execution = re_test_utils.remote_execution_linux_default(),
    deps = [
        "//folly/portability:gtest",
        "//wangle/codec:byte_to_message_decoder",
        "//wangle/codec:string_codec",
        "//wangle/service:client_dispatcher",
        "//wangle/service:close_on_release_filter",
        "//wangle/service:expiring_filter",
        "//wangle/service:server_dispatcher",
        "//wangle/service:service",
    ],
)
