load("@fbcode_macros//build_defs:cpp_binary.bzl", "cpp_binary")

oncall("fbcode_entropy_wardens_folly")

cpp_binary(
    name = "rpc_client",
    srcs = ["RpcClient.cpp"],
    headers = ["ClientSerializeHandler.h"],
    deps = [
        "//folly/init:init",
        "//folly/portability:gflags",
        "//thrift/lib/cpp2/protocol:protocol",
        "//thrift/test:thrift_test-cpp2-services",
        "//wangle/bootstrap:client_bootstrap",
        "//wangle/channel:async_socket_handler",
        "//wangle/channel:event_base_handler",
        "//wangle/channel:handler",
        "//wangle/codec:length_field_based_frame_decoder",
        "//wangle/codec:length_field_prepender",
        "//wangle/service:client_dispatcher",
        "//wangle/service:expiring_filter",
        "//wangle/service:service",
    ],
)

cpp_binary(
    name = "rpc_server",
    srcs = ["RpcServer.cpp"],
    headers = ["ServerSerializeHandler.h"],
    deps = [
        "//folly/executors:cpu_thread_pool_executor",
        "//folly/init:init",
        "//folly/portability:gflags",
        "//thrift/lib/cpp2/protocol:protocol",
        "//thrift/test:thrift_test-cpp2-services",
        "//wangle/bootstrap:server_bootstrap",
        "//wangle/channel:async_socket_handler",
        "//wangle/channel:event_base_handler",
        "//wangle/channel:handler",
        "//wangle/codec:length_field_based_frame_decoder",
        "//wangle/codec:length_field_prepender",
        "//wangle/service:executor_filter",
        "//wangle/service:server_dispatcher",
        "//wangle/service:service",
    ],
)
