load("@fbcode_macros//build_defs:cpp_binary.bzl", "cpp_binary")

oncall("fbcode_entropy_wardens_folly")

cpp_binary(
    name = "file_server",
    srcs = ["FileServer.cpp"],
    deps = [
        "//folly/init:init",
        "//folly/portability:gflags",
        "//wangle/bootstrap:server_bootstrap",
        "//wangle/channel:async_socket_handler",
        "//wangle/channel:file_region",
        "//wangle/codec:line_based_frame_decoder",
        "//wangle/codec:string_codec",
    ],
)
