load("@fbcode_macros//build_defs:cpp_binary.bzl", "cpp_binary")

oncall("fbcode_entropy_wardens_folly")

cpp_binary(
    name = "broadcast_proxy",
    srcs = ["BroadcastProxy.cpp"],
    deps = [
        "//folly/init:init",
        "//folly/portability:gflags",
        "//wangle/bootstrap:accept_routing_handler",
        "//wangle/bootstrap:routing_data_handler",
        "//wangle/bootstrap:server_bootstrap",
        "//wangle/channel:async_socket_handler",
        "//wangle/channel/broadcast:broadcast_handler",
        "//wangle/channel/broadcast:broadcast_pool",
        "//wangle/channel/broadcast:observing_handler",
        "//wangle/codec:byte_to_message_decoder",
        "//wangle/codec:message_to_byte_encoder",
    ],
)
