load("@fbcode_macros//build_defs:cpp_binary.bzl", "cpp_binary")

oncall("fbcode_entropy_wardens_folly")

cpp_binary(
    name = "proxy",
    srcs = ["Proxy.cpp"],
    deps = [
        "//folly/init:init",
        "//folly/portability:gflags",
        "//wangle/bootstrap:client_bootstrap",
        "//wangle/bootstrap:server_bootstrap",
        "//wangle/channel:async_socket_handler",
    ],
)
