load("@fbcode_macros//build_defs:cpp_binary.bzl", "cpp_binary")

oncall("fbcode_entropy_wardens_folly")

cpp_binary(
    name = "accept_server",
    srcs = ["accept_steering_server.cpp"],
    deps = [
        "//folly/init:init",
        "//folly/portability:gflags",
        "//wangle/bootstrap:accept_routing_handler",
        "//wangle/bootstrap:routing_data_handler",
        "//wangle/bootstrap:server_bootstrap",
        "//wangle/channel:async_socket_handler",
    ],
)
