load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")

oncall("fbcode_entropy_wardens_folly")

cpp_library(
    name = "client_dispatcher",
    headers = ["ClientDispatcher.h"],
    exported_deps = [
        ":service",
        "//wangle/channel:handler",
    ],
)

cpp_library(
    name = "close_on_release_filter",
    headers = ["CloseOnReleaseFilter.h"],
    exported_deps = [
        ":service",
    ],
)

cpp_library(
    name = "executor_filter",
    headers = ["ExecutorFilter.h"],
    exported_deps = [
        ":service",
    ],
)

cpp_library(
    name = "expiring_filter",
    headers = ["ExpiringFilter.h"],
    exported_deps = [
        ":service",
    ],
)

cpp_library(
    name = "server_dispatcher",
    headers = ["ServerDispatcher.h"],
    exported_deps = [
        ":service",
        "//wangle/channel:handler",
    ],
)

cpp_library(
    name = "service",
    headers = ["Service.h"],
    exported_deps = [
        "//folly:memory",
        "//folly/futures:core",
        "//wangle/bootstrap:client_bootstrap",
        "//wangle/bootstrap:server_bootstrap",
        "//wangle/channel:async_socket_handler",
        "//wangle/channel:pipeline",
    ],
)
